### ISSUE TITLE
Some remarks about the duplicate namespace

### ISSUE THREAD

**Issue by veewee** [API-Skeletons/zf-doctrine-module-zend-hydrator#1]
Hi @TomHAnderson,

I notice that the namespace is exactly the same as the DoctrineModule namespace.
This is causing some warnings:

```
composer install -o
```

> Warning: Ambiguous class resolution, "DoctrineModule\Stdlib\Hydrator\DoctrineObject" was found in both "Projects/phpro/zf-doctrine-hydration-module/vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/DoctrineObject.php" and "/Projects/phpro/zf-doctrine-hydration-module/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php", the first will be used.
> Warning: Ambiguous class resolution, "DoctrineModule\Stdlib\Hydrator\Filter\PropertyName" was found in both "/Projects/phpro/zf-doctrine-hydration-module/vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/Filter/PropertyName.php" and "/Projects/phpro/zf-doctrine-hydration-module/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/Filter/PropertyName.php", the first will be used.
> Warning: Ambiguous class resolution, "DoctrineModule\Stdlib\Hydrator\Strategy\AbstractCollectionStrategy" was found in both "/Projects/phpro/zf-doctrine-hydration-module/vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/Strategy/AbstractCollectionStrategy.php" and "/Projects/phpro/zf-doctrine-hydration-module/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/Strategy/AbstractCollectionStrategy.php", the first will be used.

As you can read, the first one is being used. In this case, this library will be used. Is this always the case?
Since this command is causing some warnings in the CLI and my editor is complaining about duplicate classes, this library might be confusing for the users. It might be a better idea to create a new namespace for these classes?

**Comment by TomHAnderson** [comment]
I didn't see this myself but I understand why it's giving the warning.  What I'm doing is exactly what it's warning about.  I'll include a description of this error as "to be expected" in the README.md file.  So even with this error which will show for most everyone the package is working as designed so long as this is included before DoctrineModule.

Creating a new namespace for the classes defeats the intention of replacing them.
