### ISSUE TITLE
README.md collaboration

### ISSUE THREAD

**Issue by TomHAnderson** [API-Skeletons/zf-doctrine-module-zend-hydrator#2]
@veewee please give a look-see at the README.md file here and offer any comments you may have.  Once we agree I'm not being an ass about the problem I'll tag 1.0

**Comment by veewee** [comment]
Thanks for the mentions! The README looks good. Let's ship it! :)

**Comment by TomHAnderson** [comment]
https://github.com/API-Skeletons/zf-doctrine-module-zend-hydrator/releases/tag/1.0.0
