### ISSUE TITLE
BC Break with last release 1.0.1

### ISSUE THREAD

**Issue by thomasvargiu** [API-Skeletons/zf-doctrine-module-zend-hydrator#7]
There is a critical BC break with the last release. It doesn't work with `json` fields.

I have an entity with a `json` type property:

```php
class Entity
{
   /**
     * @var array
     *
     * @ORM\Column(name="extras", type="json")
     */
    protected $options = [];

    /**
     * @param array $options
     */
    public function setOptions(array $options): void
    {
        $this->options = $options;
    }
}
```

The problem is in this line:
https://github.com/API-Skeletons/zf-doctrine-module-zend-hydrator/blob/1.0.1/src/DoctrineObject.php#L502

```php
    protected function handleTypeConversions($value, $typeOfField)
    {
        if (! $typeOfField) {
            return $value;
        }

        $type = Type::getType($typeOfField);
        $platform = $this->objectManager->getConnection()->getDatabasePlatform();

        return $type->convertToPHPValue($value, $platform);
    }
```

`$value` argument is an array, and `$typeOfField` argument is `json` and `$type` is and instance of `Doctrine\DBAL\Types\JsonType`.

I don't know where is the problem, but I'm trying to hydrate an object from a form (so `$options` is an `array`) and now an error occurs.

There is a different behavior and this indicates a BC break.

**Comment by TomHAnderson** [comment]
I've rolled this back to 1.0.0 with 1.0.2

The problem lies in the dbal types: https://github.com/doctrine/dbal/pull/3291
